# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Techsaui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TECHSA(object):
    def setupUi(self, TECHSA):
        TECHSA.setObjectName("TECHSA")
        TECHSA.resize(824, 600)
        self.centralwidget = QtWidgets.QWidget(TECHSA)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(6, 2, 881, 571))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:\\Dayal\\Python\\TECHSA\\VOICE REG.gif"))
        self.label.setScaledContents(False)
        self.label.setOpenExternalLinks(False)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(350, 420, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(10, 0, 171, 71))
        self.textBrowser.setStyleSheet("background-color: transparent;\n"
"font: 87 8pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);\n"
"border -radius : none;")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(10, 80, 171, 61))
        self.textBrowser_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 87 8pt \"Arial Black\";\n"
"background-color: transparent;\n"
"border -raduius : none;")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(340, 470, 131, 61))
        self.pushButton_2.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 87 14pt \"Arial Black\";")
        self.pushButton_2.setObjectName("pushButton_2")
        TECHSA.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TECHSA)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 824, 21))
        self.menubar.setObjectName("menubar")
        TECHSA.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TECHSA)
        self.statusbar.setObjectName("statusbar")
        TECHSA.setStatusBar(self.statusbar)

        self.retranslateUi(TECHSA)
        QtCore.QMetaObject.connectSlotsByName(TECHSA)

    def retranslateUi(self, TECHSA):
        _translate = QtCore.QCoreApplication.translate
        TECHSA.setWindowTitle(_translate("TECHSA", "Techsa v-2.0"))
        self.pushButton.setText(_translate("TECHSA", "LAUNCH"))
        self.pushButton_2.setText(_translate("TECHSA", "END"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TECHSA = QtWidgets.QMainWindow()
    ui = Ui_TECHSA()
    ui.setupUi(TECHSA)
    TECHSA.show()
    sys.exit(app.exec_())
